// Generated by https://quicktype.io

export interface OrderStatusesDto {
  id: number;
  step: number;
  title: string;
  description: null;
  color: string;
  count: number;
}

// Generated by https://quicktype.io

export interface GetOrdersDto {
  data: Datum[];
  links: Links;
  meta: Meta;
  status: string;
  messages: null;
}

export interface Datum {
  id: number;
  status_id: number;
  user_id: number;
  discount_code_id: null;
  code: string;
  amounts: Amounts;
  total_price: number;
  shipping_address: IngAddress;
  billing_address: IngAddress;
  delivery_at: null;
  payment_method: string;
  created_at: string;
  updated_at: string;
  bill_url: string;
  status: Status;
  business: Business;
  details: Detail[];
}

export interface Amounts {
  count: number;
  taxes: Taxes;
  sum_price: number;
  total_price: number;
  delivery_fee: number;
  product_cost: number;
  sum_discount_amount: number;
}

export interface Taxes {
  "19": number;
}

export interface IngAddress {
  type: string;
  address: string;
  city_id: number;
  default: boolean;
  location: Location;
  post_code: string;
  phone_number: string;
  recipient_name: string;
  recipient_family: string;
  [key: string]: string | boolean | Location | number;
}

export interface Location {
  latitude: string;
  longitude: string;
}

export interface Business {
  id: number;
  title: string;
  address: string;
  rate: string;
  rate_count: number;
  location: Location;
  post_code: string;
  email: string;
  logo_location: string;
  has_deposit: boolean;
  send_price: number;
  send_type: string;
  coverage_post_codes: string[];
  commission_percentage: string;
  username: string;
  created_at: string;
}

export interface Detail {
  id: number;
  order_id: number;
  business_product_id: number;
  price: number;
  discount_amount: number;
  total_price: number;
  count: number;
  total_discount_amount: null;
  created_at: string;
  updated_at: string;
  businessProduct: BusinessProduct;
}

export interface BusinessProduct {
  id: number;
  unit_value: number;
  buy_price: number;
  sell_price: number;
  discount_amount: number;
  discount_percentage: string;
  view_count: number;
  is_special: boolean;
  is_new: boolean;
  is_active: boolean;
  is_favorite: boolean;
  product: Product;
}

export interface Product {
  id: number;
  title: string;
  description: string;
  cover_location: CoverLocation;
  code: string;
  barcode: string;
  rate: string;
  rate_count: number;
  media_files: CoverLocation[];
}

export interface CoverLocation {
  id: string;
  sort_number: null;
  file_location: string;
  file_mime_type: string;
}

export interface Status {
  id: number;
  step: number;
  title: string;
  description: null;
  color: string;
}

export interface Links {
  first: string;
  last: string;
  prev: null;
  next: null;
}

export interface Meta {
  current_page: number;
  from: number;
  last_page: number;
  links: Link[];
  path: string;
  per_page: number;
  to: number;
  total: number;
}

export interface Link {
  url: null | string;
  label: string;
  active: boolean;
}

// Generated by https://quicktype.io

export interface SingleProductDto {
  id: number;
  status_id: number;
  user_id: number;
  discount_code_id: null;
  code: string;
  amounts: Amounts;
  total_price: number;
  shipping_address: IngAddress;
  billing_address: IngAddress;
  delivery_at: null;
  payment_method: string;
  created_at: string;
  updated_at: string;
  bill_url: string;
  status: Status;
  business: Business;
  details: Detail[];
  [key: string]: number | null | string | Amounts | IngAddress | Status | Business | Detail[];
}

export interface Amounts {
  count: number;
  taxes: Taxes;
  sum_price: number;
  total_price: number;
  delivery_fee: number;
  product_cost: number;
  sum_discount_amount: number;
}

export interface Taxes {
  "19": number;
}

export interface IngAddress {
  type: string;
  address: string;
  city_id: number;
  default: boolean;
  location: Location;
  post_code: string;
  phone_number: string;
  recipient_name: string;
  recipient_family: string;
}

export interface Location {
  latitude: string;
  longitude: string;
}

export interface Business {
  id: number;
  title: string;
  address: string;
  rate: string;
  rate_count: number;
  location: Location;
  post_code: string;
  email: string;
  logo_location: string;
  has_deposit: boolean;
  send_price: number;
  send_type: string;
  coverage_post_codes: string[];
  commission_percentage: string;
  username: string;
  created_at: string;
}

export interface Detail {
  id: number;
  order_id: number;
  business_product_id: number;
  price: number;
  discount_amount: number;
  total_price: number;
  count: number;
  total_discount_amount: null;
  created_at: string;
  updated_at: string;
  businessProduct: BusinessProduct;
}

export interface BusinessProduct {
  id: number;
  unit_value: number;
  buy_price: number;
  sell_price: number;
  discount_amount: number;
  discount_percentage: string;
  view_count: number;
  is_special: boolean;
  is_new: boolean;
  is_active: boolean;
  is_favorite: boolean;
  product: Product;
}

export interface Product {
  id: number;
  title: string;
  description: string;
  cover_location: CoverLocation;
  code: string;
  barcode: string;
  rate: string;
  rate_count: number;
  media_files: CoverLocation[];
}

export interface CoverLocation {
  id: string;
  sort_number: null;
  file_location: string;
  file_mime_type: string;
}

export interface Status {
  id: number;
  step: number;
  title: string;
  description: null;
  color: string;
}
