export const lorem = `لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.`;
export const postCodes = [
  { id: 25635, title: 25635 },
  { id: 56532, title: 56532 },
];

export const fakeProducts = [
  {
    id: 1,
    title: "REWE Bio Broccoli 300g",
    cover_location: "/assets/images/home/product.png",
    pricing: "300g ( 1 kg = 5.30$)",
    price: 1.59,
    discountedPrice: 1.2,
    unit: "$",
    discount: 20,
    stock: 2,
    unit_type_count: 3,
    rate: 4,
    rate_count: 4,
  },
  {
    id: 2,
    title: "REWE Bio Broccoli 300g",
    cover_location: "/assets/images/home/product.png",
    pricing: "300g ( 1 kg = 5.30$)",
    price: 1.59,
    discountedPrice: null,
    unit: "$",
    discount: null,
    stock: 2,
    unit_type_count: 3,
    rate: 4,
    rate_count: 4,
  },
  {
    id: 3,
    title: "REWE Bio Broccoli 300g",
    cover_location: "/assets/images/home/product.png",
    pricing: "300g ( 1 kg = 5.30$)",
    price: 1.59,
    discountedPrice: 1.2,
    unit: "$",
    discount: 20,
    stock: 2,
    unit_type_count: 3,
    rate: 4,
    rate_count: 4,
  },
  {
    id: 4,
    title: "REWE Bio Broccoli 300g",
    cover_location: "/assets/images/home/product.png",
    pricing: "300g ( 1 kg = 5.30$)",
    price: 1.59,
    discountedPrice: 1.2,
    unit: "$",
    discount: 20,
    stock: 2,
    unit_type_count: 3,
    rate: 4,
    rate_count: 4,
  },
  {
    id: 5,
    title: "REWE Bio Broccoli 300g",
    cover_location: "/assets/images/home/product.png",
    pricing: "300g ( 1 kg = 5.30$)",
    price: 1.59,
    discountedPrice: 1.2,
    unit: "$",
    discount: 20,
    stock: 2,
    unit_type_count: 3,
    rate: 4,
    rate_count: 4,
  },
];

export const fakeStores = [
  {
    id: 1,
    title: "Supermarket fam",
    cover_location: "/assets/images/home/fakePic.png",
    openTime: "9 - 22",
    neighbourhood: "stu Street",
    distannce: "1km",
    rate: 4,
    rate_count: 10,
    open: true,
  },
  {
    id: 2,
    title: "Supermarket fam",
    cover_location: "/assets/images/home/fakePic.png",
    openTime: " mo.9:00",
    neighbourhood: "stu Street",
    distannce: "1km",
    rate: 4,
    rate_count: 10,
    open: false,
  },
  {
    id: 3,
    title: "Supermarket fam",
    cover_location: "/assets/images/home/fakePic.png",
    openTime: "9 - 22",
    neighbourhood: "stu Street",
    distannce: "1km",
    rate: 4,
    rate_count: 10,
    open: true,
  },
  {
    id: 4,
    title: "Supermarket fam",
    cover_location: "/assets/images/home/fakePic.png",
    openTime: "9 - 22",
    neighbourhood: "stu Street",
    distannce: "1km",
    rate: 4,
    rate_count: 10,
    open: false,
  },
  {
    id: 5,
    title: "Supermarket fam",
    cover_location: "/assets/images/home/fakePic.png",
    openTime: "9 - 22",
    neighbourhood: "stu Street",
    distannce: "1km",
    rate: 4,
    rate_count: 10,
    open: true,
  },
  {
    id: 6,
    title: "Supermarket fam",
    cover_location: "/assets/images/home/fakePic.png",
    openTime: "9 - 22",
    neighbourhood: "stu Street",
    distannce: "1km",
    rate: 4,
    rate_count: 10,
    open: false,
  },
];
export const singleShop = {
  id: 6,
  title: "Supermarket fam",
  cover_location: "/assets/images/home/fakePic2.jpg",
  openTime: "9 - 22",
  neighbourhood: "stu Street",
  distannce: "1km",
  rate: 4,
  rate_count: 10,
  open: true,
  featuers: [
    { image_location: "/assets/icons/stores/vegeterian.svg", id: 123, title: "veg" },
    { image_location: "/assets/icons/stores/vegeterian.svg", id: 121, title: "veg" },
    { image_location: "/assets/icons/stores/vegeterian.svg", id: 213, title: "veg" },
    { image_location: "/assets/icons/stores/vegeterian.svg", id: 113, title: "veg" },
    { image_location: "/assets/icons/stores/vegeterian.svg", id: 121, title: "veg" },
    { image_location: "/assets/icons/stores/vegeterian.svg", id: 213, title: "veg" },
    { image_location: "/assets/icons/stores/vegeterian.svg", id: 113, title: "veg" },
  ],
};
export const fakeBrands = [
  {
    id: 1,
    title: "REWE",
    cover_location: "/assets/images/home/empty_circle.png",
    pricing: "300g ( 1 kg = 5.30$)",
  },
  {
    id: 2,
    title: "REWE",
    cover_location: "/assets/images/home/empty_circle.png",
    pricing: "300g ( 1 kg = 5.30$)",
  },
  {
    id: 3,
    title: "REWE",
    cover_location: "/assets/images/home/empty_circle.png",
    pricing: "300g ( 1 kg = 5.30$)",
  },
  {
    id: 4,
    title: "REWE",
    cover_location: "/assets/images/home/empty_circle.png",
    pricing: "300g ( 1 kg = 5.30$)",
  },
  {
    id: 5,
    title: "REWE",
    cover_location: "/assets/images/home/empty_circle.png",
    pricing: "300g ( 1 kg = 5.30$)",
  },
];
export const fakeWeight = [
  {
    id: 1,
    title: "1/5 kg",
  },
  {
    id: 2,
    title: "2/5 kg",
  },
  {
    id: 3,
    title: "15 kg",
  },
  {
    id: 4,
    title: "5 kg",
  },
  {
    id: 5,
    title: "9 kg",
  },
];

export const fakeComments = [
  {
    customer: { full_name: "Zara Alu" },
    rate: 3,
    rate_count: 2,
    title: "Lorem ipsum",
    message:
      "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs",
    created_at: Date.now(),
  },
  {
    customer: { full_name: "Zara Alu" },
    rate: 3,
    rate_count: 2,
    title: "Lorem ipsum",
    message:
      "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs",
    created_at: Date.now(),
  },
];

export const mockCategoriesTop = [
  { title: "Meat", id: 1 },
  { title: "Dairy", id: 2 },
  { title: "Drink", id: 3 },
  { title: "Frazier", id: 4 },
  { title: "Semi-prepare ", id: 5 },
];
export const fakeAttributes = {
  id: 2,
  title: "حجم",
  key: "volume",
  items: [
    {
      id: 10,
      value: "10 میل",
      description: "10 میل",
      price: 150000,
      discount_percents: null,
    },
  ],
};
export const fakeStaticSelected = {
  id: 10,
  value: "10 میل",
  description: "10 میل",
  price: 150000,
  discount_percents: null,
};
export const fakeSingleProduct = {
  id: 1,
  category_id: 11,
  package_count: 1,
  stock: 47,
  title: "REWE Bio Broccoli 300g",
  description:
    "<h1>_فری سولفات و سدیم و پارابن&nbsp;</h1>\r\n<h1>_شستسوی&nbsp; و پاک کننده ی ملایم</h1>\r\n<h1>_سرشار از روغن دانه کراتین و روغن ارگان</h1>\r\n<h1>_تحریک و تغدیه پیاز مو</h1>\r\n<h1>_افزایش گردش خون درپوست سر</h1>\r\n<h1>_افزایش رطوبت با اثرات ضد گره خوردگی و افزایش شانه پذیری ،نرمی و لطافت ساقه مو</h1>\r\n<h1>_مصرف روزانه برای انواع مو</h1>\r\n<h1>فاقد هر گونه رنگ مصنوعی ومواد شیمیایی_</h1>\r\n<h1>&nbsp;</h1>",
  code: "0X3PN",
  rate: 3,
  rate_count: 1,
  weight: "300g (1 kg = 5,30 €)",
  find: "0.1 €",
  brand: {
    // id: 2,
    // image_location: "/storage/alter/brands/brand_1674384211_13UKF.jpg",
    // title: " یر ",
    // created_at: "2022-12-07T11:57:29.000000Z",
  },
  attribue_images: ["/assets/images/mock/fresh.svg"],
  brand_id: 2,
  is_special: 1,
  is_special_discount: 40,
  made_in_country: "ایتالیا",
  cover_location: "/storage/alter/products/product_1677563888_CCHL9.png",
  created_at: "2023-01-23T12:03:48.000000Z",
  min_price: 600000,
  max_price: 600000,
  images: [
    {
      id: "/storage/alter/brands/brand_1674384211_13UKF.jpg",
      image_location: "/storage/alter/brands/brand_1674384211_13UKF.jpg",
    },
  ],
  package_type: {
    id: 5,
    title: "کارتن",
    level: 1,
    created_at: "2022-12-07T11:55:52.000000Z",
    updated_at: "2022-12-07T11:55:52.000000Z",
    deleted_at: null,
  },
  unit_type: {
    id: 6,
    title: "عدد",
    level: 2,
    created_at: "2022-12-07T11:56:07.000000Z",
    updated_at: "2022-12-07T11:56:07.000000Z",
    deleted_at: null,
  },
  status: {
    id: 20,
    step: 2,
    title: "تایید شده",
    group: "Product",
    description: null,
    color: "",
    created_at: "2022-11-29 15:58:25",
    updated_at: null,
  },
  category: {
    id: 11,
    image_location: null,
    title: "لاین کراتین",
    description: null,
    code: "2-11-",
    sort: null,
    created_at: "2023-01-23T11:56:44.000000Z",
  },
  properties: [
    {
      id: 1,
      title: "فاقد مواد شیمیایی",
      value: "فری سولفات/سدیم/پارابن/رنگ مصنوعی",
      created_at: "2023-01-23T12:06:18.000000Z",
    },
    {
      id: 5,
      title: "تراپی و احیاء",
      value: "ایجاد صافی و احیاء ساقه مو",
      created_at: "2023-01-23T12:07:16.000000Z",
    },
    {
      id: 8,
      title: "روغن تراپی",
      value: "سرشار از دانه های ارگان و کراتین",
      created_at: "2023-01-23T12:08:26.000000Z",
    },
    {
      id: 11,
      title: "رفع خشکی",
      value: "خاصیت تراپی و درمان ساقه مو و رطوبت موهای رنگ شده",
      created_at: "2023-01-23T12:10:10.000000Z",
    },
  ],
};

export const fakeCartData = {
  id: 144,
  total_price: 4,
  code: "8106317",
  deposit: "0.0",
  send_price: null,
  send_type: "tipax",
  paid_type: null,
  created_at: "2023-05-02T11:22:48.000000Z",
  paid_at: null,
  status: {
    id: 1,
    step: 1,
    title: "سبد خرید",
    group: "Order",
    description: null,
    color: "#f1c40f",
    created_at: "2022-11-29 15:58:25",
    updated_at: null,
  },
  address: null,
  orders: [
    {
      id: 290,
      order_head_id: 144,
      price: 1.59,
      discountedPrice: 1.2,
      count: 3,
      total_price: 4,
      discount_percents: null,
      created_at: "2023-05-02T11:22:48.000000Z",
      product: {
        id: 25,
        category_id: 5,
        package_count: 1,
        stock: 50,
        title: "REWE Bio Broccoli 300g",
        cover_location: "/assets/images/home/product.png",
        pricing: "300g ( 1 kg = 5.30$)",

        find: "0.1 €",
        description:
          '<div class="Info_info__1yphC TextMessage_info__1OjOW Info_default__1va1n" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: flex; align-items: center; justify-content: flex-end; height: 10px; margin: 2px 0px 6px;">\r\n<div class="MessageStateIcon_IconContainer__2c8EK" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; z-index: 1; margin-right: 3px; display: flex; flex-direction: column; align-items: center; justify-content: center; color: #000000; font-family: Shabnam; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #dcfaf5; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</div>\r\n</div>\r\n<div class="Text_text__3S-Qr TextMessage_text__1OQ_B" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; color: var(--dark-500); user-select: text; line-height: 22px; font-size: 14px; font-family: Shabnam; margin: 0px; white-space: pre-wrap; word-break: break-word;"><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">برس گرد التر هیر با قابلیت های گرمانی تحت کنترل با اثر یونی .جنس مواد اولیه فیبر کربن،لوله آلومینیومی با روکش سرامیک و تورمالین ،موهای نایلونی مقاوم در برابر حرارت سشوار تا ۲۳۰درجه باعث شده تا این برس یکی از پرفروش ترینها بازار ایران باشد</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">همچنین طراحی ارگومنیک ،دسته یه تیکه،وبدون لغزش این برس کار را برای شما آرایشگرها و مصرف کننده خانگی راحتر شود</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">به دلیل وجود مواد معدنی کریستالی در پوشش سرامیکی لوله ،گرمای سشوار به سرعت بر روی کل سطوح لوله پخش می&zwnj;شود و دما را ثابت نگه میدارد</span></div>',
        code: "CKBKJ",
        brand_id: 2,
        is_special: 1,
        is_special_discount: 0,
        made_in_country: "کره جنوبی",
        cover_location: "/storage/alter/products/product_1677342990_UH4BC.png",
        created_at: "2023-01-23T14:21:14.000000Z",
        min_price: 480000,
        max_price: 480000,
        discount: 20,
        price: 1.59,
        discountedPrice: 1.2,
      },
      attributes: [
        {
          id: 32,
          title: "سایز",
          value: "سایز63",
          description: "سایز63",
        },
      ],
    },
  ],
};

export const fakeAddresses = [
  {
    id: 3,
    full_name: "asgasga",
    mobile_number: "09128131774",
    postal_code: "156456456",
    description: "asfgasgasgasg",
    latitude: "35.770628728476",
    longitude: "51.379945278168",
    is_default: false,
    created_at: "2022-12-17T12:39:28.000000Z",
    city: {
      id: 1,
      province_id: 1,
      name: "تبریز",
      created_at: null,
      updated_at: null,
      province: {
        id: 1,
        name: "آذربایجان شرقی",
      },
    },
  },
  {
    id: 4,
    full_name: "asgasga",
    mobile_number: "09128131774",
    postal_code: "156456456",
    description: "asfgasgasgasg",
    latitude: "35.770628728476",
    longitude: "51.379945278168",
    is_default: false,
    created_at: "2022-12-17T12:39:28.000000Z",
    city: {
      id: 5,
      province_id: 1,
      name: "تبریز",
      created_at: null,
      updated_at: null,
      province: {
        id: 1,
        name: "آذربایجان شرقی",
      },
    },
  },
];

export const disposes = [
  { image_location: "/assets/images/mock/bottle.svg", title: "Glass Milk", price: 0.25, unit: "€", id: 1 },
  { image_location: "/assets/images/mock/bottle.svg", title: "Glass Milk", price: 0.25, unit: "€", id: 2 },
  { image_location: "/assets/images/mock/bottle.svg", title: "Glass Milk", price: 0.25, unit: "€", id: 3 },
  { image_location: "/assets/images/mock/bottle.svg", title: "Glass Milk", price: 0.25, unit: "€", id: 4 },
  { image_location: "/assets/images/mock/bottle.svg", title: "Glass Milk", price: 0.25, unit: "€", id: 5 },
  { image_location: "/assets/images/mock/bottle.svg", title: "Glass Milk", price: 0.25, unit: "€", id: 6 },
  { image_location: "/assets/images/mock/bottle.svg", title: "Glass Milk", price: 0.25, unit: "€", id: 7 },
  { image_location: "/assets/images/mock/bottle.svg", title: "Glass Milk", price: 0.25, unit: "€", id: 8 },
  { image_location: "/assets/images/mock/bottle.svg", title: "Glass Milk", price: 0.25, unit: "€", id: 9 },
];

export const mockActiveOrder = {
  order_number: 978030,
  order_date: "02/03/2023 16:58",
  store_name: "hyper Market",
  store_tell: 12424142124,
  drivers_name: "Saeed Mohammadi",
  buyers_name: "Ali Alipour",
  buyers_tel: 124124124,
  buyers_address: "German , Zabeel, Al-Mustakbal St",
  order_status: "delivered",
  deliver_plan: "Monday 12:00 - 14:00",
};

export const mockUserCards = [
  { number: "•••• •••• •••• 4679", image_location: "/assets/icons/profile/master_card.svg", id: 1 },
  { number: "•••• •••• •••• 4615", image_location: "/assets/icons/profile/master_card.svg", id: 2 },
];

export const mockHistoryItems = [
  { date: "01/02/2023 - 15 :10", amount: "500 $", id: 1 },
  { date: "11/04/2023 - 15 :10", amount: "500 $", id: 2 },
];

export const fakeTickets = [
  { title: "Title: How Can I order a new space in Livin Room ? ", id: 1, created_at: "12/07/2022  21:12" },
  { title: "Title: How Can I order a new space in Livin Room ? ", id: 2, created_at: "12/07/2022  21:12" },
];
export const fakeSingleTicket = {
  title: "Title: How Can I order a new space in Livin Room ? ",
  id: 2,
  created_at: "12/07/2022  21:12",
  description:
    "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.  ",
  Response: {
    name: "Ali Alizadeh",
    message:
      "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.  ",
  },
};

export const fakeOrdersHeader = [
  {
    id: 1,
    step: 1,
    title: "Waiting for payment",
    description: null,
    color: "string",
    count: 0,
  },
  {
    id: 2,
    step: 2,
    title: "Processing",
    description: null,
    color: "string",
    count: 0,
  },
  {
    id: 3,
    step: 3,
    title: "Delivered",
    description: null,
    color: "string",
    count: 2,
  },
  {
    id: 4,
    step: 4,
    title: "Canceled",
    description: null,
    color: "string",
    count: 2,
  },
  {
    id: 5,
    step: 45,
    title: "Return",
    description: null,
    color: "string",
    count: 2,
  },
];

export const fakeOrders = [
  {
    id: 24,
    total_price: 124,
    code: "8106317",
    market_name: "Supermarket fam",
    send_price: 0,
    send_type: "post",
    paid_type: null,
    created_at: "2023-05-02T11:22:48.000000Z",
    paid_at: null,
    can_pay: false,
    status: {
      id: 3,
      step: 20,
      title: "در انتظار پرداخت",
      group: "Order",
      description: null,
      color: "",
      created_at: "2022-11-29 15:58:25",
      updated_at: null,
    },
    address: {
      id: 2124,
      order_head_id: 144,
      city_id: 1,
      address: "asfgasgasgasg",
      latitude: "35.770628728476",
      longitude: "51.379945278168",
      mobile_number: "09128131774",
      full_name: "asgasga",
      created_at: "2023-05-06T08:48:41.000000Z",
      updated_at: "2023-05-06T08:48:41.000000Z",
    },
    orders: [
      {
        id: 124,
        order_head_id: 144,
        price: 600000,
        count: 3,
        total_price: 1800000,
        discount_percents: null,
        created_at: "2023-05-02T11:22:48.000000Z",
        product: {
          id: 151,
          category_id: 5,
          package_count: 1,
          stock: 50,
          title: "برس گرد طلایی (سایز6)",
          description:
            '<div class="Info_info__1yphC TextMessage_info__1OjOW Info_default__1va1n" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: flex; align-items: center; justify-content: flex-end; height: 10px; margin: 2px 0px 6px;">\r\n<div class="MessageStateIcon_IconContainer__2c8EK" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; z-index: 1; margin-right: 3px; display: flex; flex-direction: column; align-items: center; justify-content: center; color: #000000; font-family: Shabnam; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #dcfaf5; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</div>\r\n</div>\r\n<div class="Text_text__3S-Qr TextMessage_text__1OQ_B" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; color: var(--dark-500); user-select: text; line-height: 22px; font-size: 14px; font-family: Shabnam; margin: 0px; white-space: pre-wrap; word-break: break-word;"><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">برس گرد التر هیر با قابلیت های گرمانی تحت کنترل با اثر یونی .جنس مواد اولیه فیبر کربن،لوله آلومینیومی با روکش سرامیک و تورمالین ،موهای نایلونی مقاوم در برابر حرارت سشوار تا ۲۳۰درجه باعث شده تا این برس یکی از پرفروش ترینها بازار ایران باشد</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">همچنین طراحی ارگومنیک ،دسته یه تیکه،وبدون لغزش این برس کار را برای شما آرایشگرها و مصرف کننده خانگی راحتر شود</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">به دلیل وجود مواد معدنی کریستالی در پوشش سرامیکی لوله ،گرمای سشوار به سرعت بر روی کل سطوح لوله پخش می&zwnj;شود و دما را ثابت نگه میدارد</span></div>',
          code: "CKBKJ",
          brand_id: 2,
          is_special: 1,
          is_special_discount: 0,
          made_in_country: "کره جنوبی",
          cover_location: "/storage/alter/products/product_1677342990_UH4BC.png",
          created_at: "2023-01-23T14:21:14.000000Z",
          min_price: 480000,
          max_price: 480000,
        },
        attributes: [
          {
            id: 235,
            title: "سایز",
            value: "سایز63",
            description: "سایز63",
          },
        ],
      },
    ],
  },
  {
    id: 235,
    total_price: 124,
    code: "8106317",
    market_name: "Supermarket fam",
    send_price: 0,
    send_type: "post",
    paid_type: null,
    created_at: "2023-05-02T11:22:48.000000Z",
    paid_at: null,
    can_pay: false,
    status: {
      id: 32,
      step: 20,
      title: "در انتظار پرداخت",
      group: "Order",
      description: null,
      color: "",
      created_at: "2022-11-29 15:58:25",
      updated_at: null,
    },
    address: {
      id: 236,
      order_head_id: 144,
      city_id: 1,
      address: "asfgasgasgasg",
      latitude: "35.770628728476",
      longitude: "51.379945278168",
      mobile_number: "09128131774",
      full_name: "asgasga",
      created_at: "2023-05-06T08:48:41.000000Z",
      updated_at: "2023-05-06T08:48:41.000000Z",
    },
    orders: [
      {
        id: 457,
        order_head_id: 144,
        price: 600000,
        count: 3,
        total_price: 1800000,
        discount_percents: null,
        created_at: "2023-05-02T11:22:48.000000Z",
        product: {
          id: 34,
          category_id: 5,
          package_count: 1,
          stock: 50,
          title: "برس گرد طلایی (سایز6)",
          description:
            '<div class="Info_info__1yphC TextMessage_info__1OjOW Info_default__1va1n" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: flex; align-items: center; justify-content: flex-end; height: 10px; margin: 2px 0px 6px;">\r\n<div class="MessageStateIcon_IconContainer__2c8EK" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; z-index: 1; margin-right: 3px; display: flex; flex-direction: column; align-items: center; justify-content: center; color: #000000; font-family: Shabnam; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #dcfaf5; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</div>\r\n</div>\r\n<div class="Text_text__3S-Qr TextMessage_text__1OQ_B" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; color: var(--dark-500); user-select: text; line-height: 22px; font-size: 14px; font-family: Shabnam; margin: 0px; white-space: pre-wrap; word-break: break-word;"><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">برس گرد التر هیر با قابلیت های گرمانی تحت کنترل با اثر یونی .جنس مواد اولیه فیبر کربن،لوله آلومینیومی با روکش سرامیک و تورمالین ،موهای نایلونی مقاوم در برابر حرارت سشوار تا ۲۳۰درجه باعث شده تا این برس یکی از پرفروش ترینها بازار ایران باشد</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">همچنین طراحی ارگومنیک ،دسته یه تیکه،وبدون لغزش این برس کار را برای شما آرایشگرها و مصرف کننده خانگی راحتر شود</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">به دلیل وجود مواد معدنی کریستالی در پوشش سرامیکی لوله ،گرمای سشوار به سرعت بر روی کل سطوح لوله پخش می&zwnj;شود و دما را ثابت نگه میدارد</span></div>',
          code: "CKBKJ",
          brand_id: 2,
          is_special: 1,
          is_special_discount: 0,
          made_in_country: "کره جنوبی",
          cover_location: "/storage/alter/products/product_1677342990_UH4BC.png",
          created_at: "2023-01-23T14:21:14.000000Z",
          min_price: 480000,
          max_price: 480000,
        },
        attributes: [
          {
            id: 457,
            title: "سایز",
            value: "سایز63",
            description: "سایز63",
          },
        ],
      },
      {
        id: 236457,
        order_head_id: 144,
        price: 600000,
        count: 3,
        total_price: 1800000,
        discount_percents: null,
        created_at: "2023-05-02T11:22:48.000000Z",
        product: {
          id: 25,
          category_id: 5,
          package_count: 1,
          stock: 50,
          title: "برس گرد طلایی (سایز6)",
          description:
            '<div class="Info_info__1yphC TextMessage_info__1OjOW Info_default__1va1n" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: flex; align-items: center; justify-content: flex-end; height: 10px; margin: 2px 0px 6px;">\r\n<div class="MessageStateIcon_IconContainer__2c8EK" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; z-index: 1; margin-right: 3px; display: flex; flex-direction: column; align-items: center; justify-content: center; color: #000000; font-family: Shabnam; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #dcfaf5; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</div>\r\n</div>\r\n<div class="Text_text__3S-Qr TextMessage_text__1OQ_B" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; color: var(--dark-500); user-select: text; line-height: 22px; font-size: 14px; font-family: Shabnam; margin: 0px; white-space: pre-wrap; word-break: break-word;"><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">برس گرد التر هیر با قابلیت های گرمانی تحت کنترل با اثر یونی .جنس مواد اولیه فیبر کربن،لوله آلومینیومی با روکش سرامیک و تورمالین ،موهای نایلونی مقاوم در برابر حرارت سشوار تا ۲۳۰درجه باعث شده تا این برس یکی از پرفروش ترینها بازار ایران باشد</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">همچنین طراحی ارگومنیک ،دسته یه تیکه،وبدون لغزش این برس کار را برای شما آرایشگرها و مصرف کننده خانگی راحتر شود</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">به دلیل وجود مواد معدنی کریستالی در پوشش سرامیکی لوله ،گرمای سشوار به سرعت بر روی کل سطوح لوله پخش می&zwnj;شود و دما را ثابت نگه میدارد</span></div>',
          code: "CKBKJ",
          brand_id: 2,
          is_special: 1,
          is_special_discount: 0,
          made_in_country: "کره جنوبی",
          cover_location: "/storage/alter/products/product_1677342990_UH4BC.png",
          created_at: "2023-01-23T14:21:14.000000Z",
          min_price: 480000,
          max_price: 480000,
        },
        attributes: [
          {
            id: 32,
            title: "سایز",
            value: "سایز63",
            description: "سایز63",
          },
        ],
      },
      {
        id: 290,
        order_head_id: 144,
        price: 600000,
        count: 3,
        total_price: 1800000,
        discount_percents: null,
        created_at: "2023-05-02T11:22:48.000000Z",
        product: {
          id: 25,
          category_id: 5,
          package_count: 1,
          stock: 50,
          title: "برس گرد طلایی (سایز6)",
          description:
            '<div class="Info_info__1yphC TextMessage_info__1OjOW Info_default__1va1n" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: flex; align-items: center; justify-content: flex-end; height: 10px; margin: 2px 0px 6px;">\r\n<div class="MessageStateIcon_IconContainer__2c8EK" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; z-index: 1; margin-right: 3px; display: flex; flex-direction: column; align-items: center; justify-content: center; color: #000000; font-family: Shabnam; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #dcfaf5; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</div>\r\n</div>\r\n<div class="Text_text__3S-Qr TextMessage_text__1OQ_B" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; color: var(--dark-500); user-select: text; line-height: 22px; font-size: 14px; font-family: Shabnam; margin: 0px; white-space: pre-wrap; word-break: break-word;"><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">برس گرد التر هیر با قابلیت های گرمانی تحت کنترل با اثر یونی .جنس مواد اولیه فیبر کربن،لوله آلومینیومی با روکش سرامیک و تورمالین ،موهای نایلونی مقاوم در برابر حرارت سشوار تا ۲۳۰درجه باعث شده تا این برس یکی از پرفروش ترینها بازار ایران باشد</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">همچنین طراحی ارگومنیک ،دسته یه تیکه،وبدون لغزش این برس کار را برای شما آرایشگرها و مصرف کننده خانگی راحتر شود</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">به دلیل وجود مواد معدنی کریستالی در پوشش سرامیکی لوله ،گرمای سشوار به سرعت بر روی کل سطوح لوله پخش می&zwnj;شود و دما را ثابت نگه میدارد</span></div>',
          code: "CKBKJ",
          brand_id: 2,
          is_special: 1,
          is_special_discount: 0,
          made_in_country: "کره جنوبی",
          cover_location: "/storage/alter/products/product_1677342990_UH4BC.png",
          created_at: "2023-01-23T14:21:14.000000Z",
          min_price: 480000,
          max_price: 480000,
        },
        attributes: [
          {
            id: 32,
            title: "سایز",
            value: "سایز63",
            description: "سایز63",
          },
        ],
      },
      {
        id: 22490,
        order_head_id: 144,
        price: 600000,
        count: 3,
        total_price: 1800000,
        discount_percents: null,
        created_at: "2023-05-02T11:22:48.000000Z",
        product: {
          id: 25,
          category_id: 5,
          package_count: 1,
          stock: 50,
          title: "برس گرد طلایی (سایز6)",
          description:
            '<div class="Info_info__1yphC TextMessage_info__1OjOW Info_default__1va1n" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: flex; align-items: center; justify-content: flex-end; height: 10px; margin: 2px 0px 6px;">\r\n<div class="MessageStateIcon_IconContainer__2c8EK" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; z-index: 1; margin-right: 3px; display: flex; flex-direction: column; align-items: center; justify-content: center; color: #000000; font-family: Shabnam; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #dcfaf5; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</div>\r\n</div>\r\n<div class="Text_text__3S-Qr TextMessage_text__1OQ_B" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; color: var(--dark-500); user-select: text; line-height: 22px; font-size: 14px; font-family: Shabnam; margin: 0px; white-space: pre-wrap; word-break: break-word;"><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">برس گرد التر هیر با قابلیت های گرمانی تحت کنترل با اثر یونی .جنس مواد اولیه فیبر کربن،لوله آلومینیومی با روکش سرامیک و تورمالین ،موهای نایلونی مقاوم در برابر حرارت سشوار تا ۲۳۰درجه باعث شده تا این برس یکی از پرفروش ترینها بازار ایران باشد</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">همچنین طراحی ارگومنیک ،دسته یه تیکه،وبدون لغزش این برس کار را برای شما آرایشگرها و مصرف کننده خانگی راحتر شود</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">به دلیل وجود مواد معدنی کریستالی در پوشش سرامیکی لوله ،گرمای سشوار به سرعت بر روی کل سطوح لوله پخش می&zwnj;شود و دما را ثابت نگه میدارد</span></div>',
          code: "CKBKJ",
          brand_id: 2,
          is_special: 1,
          is_special_discount: 0,
          made_in_country: "کره جنوبی",
          cover_location: "/storage/alter/products/product_1677342990_UH4BC.png",
          created_at: "2023-01-23T14:21:14.000000Z",
          min_price: 480000,
          max_price: 480000,
        },
        attributes: [
          {
            id: 32,
            title: "سایز",
            value: "سایز63",
            description: "سایز63",
          },
        ],
      },
    ],
  },
];

export const fakeSingleOrder = {
  id: 144,
  total_price: 1800000,
  code: "8106317",
  send_price: 0,
  send_type: "post",
  paid_type: null,
  created_at: "2023-05-02T11:22:48.000000Z",
  paid_at: null,
  can_cancel: true,
  can_pay: false,
  status: {
    id: 3,
    step: 20,
    title: "در انتظار پرداخت",
    group: "Order",
    description: null,
    color: "",
    created_at: "2022-11-29 15:58:25",
    updated_at: null,
  },
  address: {
    id: 107,
    order_head_id: 144,
    city_id: 1,
    address: "asfgasgasgasg",
    latitude: "35.770628728476",
    longitude: "51.379945278168",
    mobile_number: "09128131774",
    full_name: "asgasga",
    created_at: "2023-05-06T08:48:41.000000Z",
    updated_at: "2023-05-06T08:48:41.000000Z",
  },
  orders: [
    {
      id: 290,
      order_head_id: 144,
      price: 600000,
      count: 3,
      total_price: 1800000,
      discount_percents: null,
      created_at: "2023-05-02T11:22:48.000000Z",
      product: {
        id: 25,
        category_id: 5,
        package_count: 1,
        stock: 50,
        title: "برس گرد طلایی (سایز6)",
        description:
          '<div class="Info_info__1yphC TextMessage_info__1OjOW Info_default__1va1n" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: flex; align-items: center; justify-content: flex-end; height: 10px; margin: 2px 0px 6px;">\r\n<div class="MessageStateIcon_IconContainer__2c8EK" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; z-index: 1; margin-right: 3px; display: flex; flex-direction: column; align-items: center; justify-content: center; color: #000000; font-family: Shabnam; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #dcfaf5; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</div>\r\n</div>\r\n<div class="Text_text__3S-Qr TextMessage_text__1OQ_B" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; color: var(--dark-500); user-select: text; line-height: 22px; font-size: 14px; font-family: Shabnam; margin: 0px; white-space: pre-wrap; word-break: break-word;"><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">برس گرد التر هیر با قابلیت های گرمانی تحت کنترل با اثر یونی .جنس مواد اولیه فیبر کربن،لوله آلومینیومی با روکش سرامیک و تورمالین ،موهای نایلونی مقاوم در برابر حرارت سشوار تا ۲۳۰درجه باعث شده تا این برس یکی از پرفروش ترینها بازار ایران باشد</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">همچنین طراحی ارگومنیک ،دسته یه تیکه،وبدون لغزش این برس کار را برای شما آرایشگرها و مصرف کننده خانگی راحتر شود</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">به دلیل وجود مواد معدنی کریستالی در پوشش سرامیکی لوله ،گرمای سشوار به سرعت بر روی کل سطوح لوله پخش می&zwnj;شود و دما را ثابت نگه میدارد</span></div>',
        code: "CKBKJ",
        brand_id: 2,
        is_special: 1,
        is_special_discount: 0,
        made_in_country: "کره جنوبی",
        cover_location: "/storage/alter/products/product_1677342990_UH4BC.png",
        created_at: "2023-01-23T14:21:14.000000Z",
        min_price: 480000,
        max_price: 480000,
      },
      attributes: [
        {
          id: 32,
          title: "سایز",
          value: "سایز63",
          description: "سایز63",
        },
      ],
    },
    {
      id: 2425,
      order_head_id: 144,
      price: 600000,
      count: 3,
      total_price: 1800000,
      discount_percents: null,
      created_at: "2023-05-02T11:22:48.000000Z",
      product: {
        id: 25,
        category_id: 5,
        package_count: 1,
        stock: 50,
        title: "برس گرد طلایی (سایز6)",
        description:
          '<div class="Info_info__1yphC TextMessage_info__1OjOW Info_default__1va1n" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: flex; align-items: center; justify-content: flex-end; height: 10px; margin: 2px 0px 6px;">\r\n<div class="MessageStateIcon_IconContainer__2c8EK" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; z-index: 1; margin-right: 3px; display: flex; flex-direction: column; align-items: center; justify-content: center; color: #000000; font-family: Shabnam; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #dcfaf5; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</div>\r\n</div>\r\n<div class="Text_text__3S-Qr TextMessage_text__1OQ_B" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; color: var(--dark-500); user-select: text; line-height: 22px; font-size: 14px; font-family: Shabnam; margin: 0px; white-space: pre-wrap; word-break: break-word;"><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">برس گرد التر هیر با قابلیت های گرمانی تحت کنترل با اثر یونی .جنس مواد اولیه فیبر کربن،لوله آلومینیومی با روکش سرامیک و تورمالین ،موهای نایلونی مقاوم در برابر حرارت سشوار تا ۲۳۰درجه باعث شده تا این برس یکی از پرفروش ترینها بازار ایران باشد</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">همچنین طراحی ارگومنیک ،دسته یه تیکه،وبدون لغزش این برس کار را برای شما آرایشگرها و مصرف کننده خانگی راحتر شود</span><span class="p" dir="rtl" style="outline: none; -webkit-tap-highlight-color: transparent; box-sizing: border-box; display: block;">به دلیل وجود مواد معدنی کریستالی در پوشش سرامیکی لوله ،گرمای سشوار به سرعت بر روی کل سطوح لوله پخش می&zwnj;شود و دما را ثابت نگه میدارد</span></div>',
        code: "CKBKJ",
        brand_id: 2,
        is_special: 1,
        is_special_discount: 0,
        made_in_country: "کره جنوبی",
        cover_location: "/storage/alter/products/product_1677342990_UH4BC.png",
        created_at: "2023-01-23T14:21:14.000000Z",
        min_price: 480000,
        max_price: 480000,
      },
      attributes: [
        {
          id: 32,
          title: "سایز",
          value: "سایز63",
          description: "سایز63",
        },
      ],
    },
  ],
};

export const fakeUserCards = [
  { title: "Paypal", id: 1 },
  { title: "Ec card", id: 2 },
  { title: "Credit card", id: 3 },
  { title: "Cash", id: 4 },
];
